"""Basic models

Revision ID: dffd6836dd2b
Revises: 
Create Date: 2020-06-01 15:13:19.462983

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "dffd6836dd2b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "make",
        sa.Column("pk", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_index(op.f("ix_make_active"), "make", ["active"], unique=False)
    op.create_table(
        "model",
        sa.Column("pk", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("make_pk", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["make_pk"], ["make.pk"],),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_index(op.f("ix_model_active"), "model", ["active"], unique=False)
    op.create_index(op.f("ix_model_make_pk"), "model", ["make_pk"], unique=False)
    op.create_table(
        "submodel",
        sa.Column("pk", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("model_pk", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["model_pk"], ["model.pk"],),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "car",
        sa.Column("pk", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("mileage", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("exterior_color", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("submodel_pk", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "body_type",
            sa.Enum("COUPE", "SEDAN", "SUV", "HATCHBACK", "CONVERTIBLE", name="bodytype"),
            nullable=True,
        ),
        sa.Column(
            "transmission",
            sa.Enum("AUTOMATIC", "MANUAL", name="transmission"),
            nullable=True,
        ),
        sa.Column(
            "fuel_type", sa.Enum("PETROL", "HYBRID", name="fueltype"), nullable=True
        ),
        sa.ForeignKeyConstraint(["submodel_pk"], ["submodel.pk"],),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_index(op.f("ix_car_active"), "car", ["active"], unique=False)
    op.create_index(op.f("ix_car_submodel_pk"), "car", ["submodel_pk"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_car_submodel_pk"), table_name="car")
    op.drop_index(op.f("ix_car_active"), table_name="car")
    op.drop_table("car")
    op.drop_table("submodel")
    op.drop_index(op.f("ix_model_make_pk"), table_name="model")
    op.drop_index(op.f("ix_model_active"), table_name="model")
    op.drop_table("model")
    op.drop_index(op.f("ix_make_active"), table_name="make")
    op.drop_table("make")
    # ### end Alembic commands ###
